### PR TITLE
doc: make events in the document clearer

### LINKED ISSUE #412: Make "events" in the document even clearer
Currently, we are using the term "event" for both Events API data and any incoming payload requests from Slack in the Bolt document. For example,

* There is the "Listening to events" section: https://slack.dev/bolt-python/concepts#event-listening which is referring to the Events API
* Then there is the "Acknowledging events" section: https://slack.dev/bolt-python/concepts#acknowledge which is referring to actions, shortcuts, commands, and options. Also, Bolt acknowledges the "events" for Events API under the hood.

This can be confusing for developers especially when they are not yet familiar with the Slack Platform yet.

To improve this, we can consistently use the term "request" for incoming requests from Slack. Specifically, 

* We can rename the section "Acknowledging events" to "Acknowledging requests"
* We can replace all the phrases like "acknowledging events" to "acknowledge requests" in all sections

### The page URLs

* https://slack.dev/bolt-python/concepts#acknowledge and others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

### PR DESCRIPTION
**Pull request by RhnSharma**
Fixes #412
Hi @seratch, how does this look?
Let me know if this needs any changes.
Thanks

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [x] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

### CODE REVIEW

**Comment by seratch** [comment]
Hi @RhnSharma, thanks for taking the time to make this pull request! Perhaps, there may be more to change in the documents. I would like other maintainers to check this first.

**Review by stevengill — CHANGES_REQUESTED** [review]
Hey @RhnSharma! 

Thank you so much for sending this in! I left a few comments on other instances of events we can update.

Also, to close the issue, we should look into updating these files as well.

* https://slack.dev/bolt-python/concepts#action-listening - this references acknowledging events section and also uses the word events which should be changes to requests
* https://slack.dev/bolt-python/concepts#action-respond - uses event, should be replaced to request
* https://slack.dev/bolt-python/concepts#adapters - three instances of events -> requests
* https://slack.dev/bolt-python/concepts#authorization - three instances of events -> requests
* https://slack.dev/bolt-python/concepts#global-middleware - once instance of events -> requests 
* https://slack.dev/bolt-python/concepts#context - two instances to update
* https://slack.dev/bolt-python/concepts#lazy-listeners - three of the four instances should be updated to requests. I'd leave `For events, while a listener doesn’t need ack() method` events reference alone

**Comment by RhnSharma** [comment]
@stevengill I have made the changes you suggested. Please take a look at it and let me know if this needs any changes.
Thanks

**Review by seratch — APPROVED** [review]

**Comment by seratch** [comment]
@stevengill This pull request now looks good to me. Do you have any comments on it?

**Comment by seratch** [comment]
Will merge this pull request tomorrow if there is no other comment

**Comment by seratch** [comment]
@RhnSharma Thanks a lot for making this pull request 👍

**Pull request merged**
