### PR TITLE
Added basic lazy lambda example setup and deploy instructions

### PR DESCRIPTION
**Pull request by filmaj**
Also fixed vendor module import issues; based on the [Create python package with dependencies AWS docs for Lambda](https://docs.aws.amazon.com/lambda/latest/dg/python-package-create.html#python-package-create-with-dependency), any dependencies need to exist in the root of the package. The changes in this PR are the changes I needed to incorporate to help me run the lazy example. I also tried to document my setup journey in a README in this directory.

This PR is based on trying to help out with #440.

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [x] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

### CODE REVIEW

**Review by seratch — APPROVED** [review]
Thank you! Having `vendor` directory used to work but perhaps, it's no longer compatible with the tool.

**Comment by seratch** [comment]
oops, I forgot to mention the OAuth example. We can update the vendor directory part for the example too. https://github.com/slackapi/bolt-python/blob/main/examples/aws_lambda/aws_lambda_oauth_config.yaml

**Comment by filmaj** [comment]
Sounds good, will do

**Comment by filmaj** [comment]
Opened #444

**Pull request merged**
