### PR TITLE
Fixed fetching of names for callable objects (#215)

### PR DESCRIPTION
**Pull request by nickovs**
Added new function name_for_callable() in util.utils.
Fixed name properties for CustomMiddleware and AsyncCustomMiddleware to use the new function.
Modified listener/thread_runner.py and listener/asyncio_runner.py to use the new function to name lazy functions.
Added test cases for middleware and lazy function cases.

This addresses the issue in #215.

### Category (place an `x` in each of the `[ ]`)

* [x] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

### CODE REVIEW

**Comment by mwbrooks** [comment]
Thanks for the PR @nickovs! 🎸 

When you have a moment, would you mind signing the CLA so that we can merge your work? It's quick and digital, just select the [link from the CLAssistant](https://github.com/slackapi/bolt-python/pull/216#issuecomment-763260351).

In the meantime, we'll review it and let the CI run the tests 🙂

**Comment by nickovs** [comment]
@mwbrooks I have signed the CLA. There seems to be a bug in your CLA assistant. There are two different email addresses in my commits (one home, one work). Both are linked to my GitHub account and the commit history for my branch correctly shows both commits as belonging to the @nickovs user, but for some reason the CLA Assistant is only showing one identity as having signed the CLA. When I click on the link to sign it again it says that I have already signed the CLA and won't let me Sogn it again.

**Comment by seratch** [comment]
@nickovs Could you squash them into one commit using the email address used for signing the CLA?

**Comment by nickovs** [comment]
OK. I did a `git commit --amend ...` and that seems to have satisfied the CLA Assistant.

**Comment by seratch** [comment]
@nickovs Thanks for promptly submitting this PR! I am going to check this in detail later today (I live in +09:00 timezone). One thing, it seems the following tests for adapters fro AWS Lamdba are failing. Have you already checked this out?

```
FAILED tests/adapter_tests/test_aws_chalice.py::TestAwsChalice::test_lazy_listeners
FAILED tests/adapter_tests/test_aws_lambda.py::TestAWSLambda::test_lazy_listeners
```

**Comment by nickovs** [comment]
@seratch Regarding the tests, I just noticed that. When I run the tests locally, whether on the main branch or on my new code, several of the tests are very unreliable, frequently failing with `ConnectionResetError: [Errno 54] Connection reset by peer` exceptions trying to talk to the mock servers. I was just trying to separate out if these issues in the lazy listeners are to do with my code or the generally flakey test harness.

**Comment by seratch** [comment]
>several of the tests are very unreliable, frequently failing with ConnectionResetError: [Errno 54] Connection reset by peer exceptions trying to talk to the mock servers.

Yes ... this is a known issue that happens on local machine. https://github.com/slackapi/bolt-python/issues/157 

Re-running the same tests by `./scripts/run_tests.sh {test file path}` should help for most cases. e.g.,

```
./scripts/run_tests.sh tests/adapter_tests/test_aws_chalice.py
./scripts/run_tests.sh tests/adapter_tests/
```

**Comment by nickovs** [comment]
Actually it was just a dumb cut-and-paste error. I've pushed a fix.

I added type hints to the new `name_for_callable()` utility function while I was there.

**Review by seratch — APPROVED** [review]

**Comment by seratch** [comment]
Thanks - LGTM

**Pull request merged**
