### PR TITLE
Change AWS API Gateway to Lambda Function URL

### PR DESCRIPTION
**Pull request by Globart1337**
Update "AWS Lambda Bolt Python Examples" page to include Lambda URL

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [ ] Document pages under `/docs`
* [x] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

### CODE REVIEW

**Comment by seratch** [comment]
@Globart1337 Thank you very much for submitting this PR quickly! Since I live in a bit different timezone (+09:00), I am unable to check your pull request now. My teammates may be able to check this PR today.

One thing that I would like to ask you is to check the above comment by CLA bot. We are unable to merge your contributions without your CLA signature. Please check the CLA content and consider signing it 🙇

**Comment by Globart1337** [comment]
> @Globart1337 Thank you very much for submitting this PR quickly! Since I live in a bit different timezone (+09:00), I am unable to check your pull request now. My teammates may be able to check this PR today.
> 
> One thing that I would like to ask you is to check the above comment by CLA bot. We are unable to merge your contributions without your CLA signature. Please check the CLA content and consider signing it bow

signed :heavy_check_mark:

**Review by filmaj — CHANGES_REQUESTED** [review]
Hey I tested this out and this is working great! Huge improvement, and simpler setup. I like this a lot 👍 

The only request I would have is that at the top of this document, between lines 6 and 11, there are still a few references to API Gateway. Can we update those, please?

**Comment by Globart1337** [comment]
> Hey I tested this out and this is working great! Huge improvement, and simpler setup. I like this a lot 👍
> 
> The only request I would have is that at the top of this document, between lines 6 and 11, there are still a few references to API Gateway. Can we update those, please?

Oh, didn't see them, will make an update

**Comment by Globart1337** [comment]
@filmaj please review

**Comment by Globart1337** [comment]
@seratch please review the change to PR or atleast ping @filmaj

**Review by seratch — APPROVED** [review]
Thanks for updating this PR. Looks good to me 👍

**Comment by filmaj** [comment]
Thanks a lot for this @Globart1337 ! Sorry I didn't respond earlier: it was my weekend so I try to stay away from the computer 😄

**Comment by Globart1337** [comment]
> Thanks a lot for this @Globart1337 ! Sorry I didn't respond earlier: it was my weekend so I try to stay away from the computer 😄

Oh, okay then, no worries 😃

**Pull request merged**
