### PR TITLE
Added redirect url to readme

### LINKED ISSUE #829: How would organizations install the app/bot?
The Django example is vaguely written and doesn't explain how the flow for oauth should be. How does another organisation install an app? I can't just DM them the install URL. Also, why was it created when the app can be installed from the slack app store? I've installed my app into the workspace i am using already so I am wondering what the install endpoint is for. Please explain the flow clearly.

### PR DESCRIPTION
**Pull request by Smyja**
Fixes #829

### CODE REVIEW

**Review by seratch — APPROVED** [review]
Thank you! LGTM

**Comment by seratch** [comment]
Hi @Smyja, we apologize for the inconvenience, but we kindly ask that you sign our new CLA: https://cla.salesforce.com/status/slackapi/bolt-python/pull/893

As it is not fully compatible with the previous agreement you signed for this PR, we need your signature once again. Your cooperation and prompt response would be greatly appreciated.

**Comment by Smyja** [comment]
> Hi @Smyja, we apologize for the inconvenience, but we kindly ask that you sign our new CLA: https://cla.salesforce.com/status/slackapi/bolt-python/pull/893
> 
> As it is not fully compatible with the previous agreement you signed for this PR, we need your signature once again. Your cooperation and prompt response would be greatly appreciated. 



I have signed it before, nothing new shows on the page.

**Comment by seratch** [comment]
@Smyja can you visit the link labeled "sign the CLA"? https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fslackapi%2Fbolt-python%2Fpull%2F893

**Comment by Smyja** [comment]
> @Smyja can you visit the link labeled "sign the CLA"? https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Fslackapi%2Fbolt-python%2Fpull%2F893



It shows that when I link my github.

**Comment by seratch** [comment]
@Smyja Ah, you're right and I appreciate it 🙇 No further action is needed for you. So sorry for the confusion!

**Pull request merged**
