### PR TITLE
Adds line wrapping to code samples

### PR DESCRIPTION
**Pull request by shaydewael**
Some of the long lines are hard to read in current documentation. This PR adds line wrapping to make it easier 😄 

### Current
image

### PR
image

### Category (place an `x` in each of the `[ ]`)

* [ ] `slack_bolt.App` and/or its core components
* [ ] `slack_bolt.async_app.AsyncApp` and/or its core components
* [ ] Adapters in `slack_bolt.adapter`
* [x] Document pages under `/docs`
* [ ] Others

## Requirements (place an `x` in each `[ ]`)

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've run `./scripts/install_all_and_run_tests.sh` after making the changes.

### CODE REVIEW

**Comment by seratch** [comment]
Line 2 starting with "responds with" is not a new line. Is it possible not to have the line number for the wrapped part?

**Comment by shaydewael** [comment]
@seratch Hmmm unfortunately the line wrapping is done with CSS where the line numbers are added via kramdown, so I don't believe it would be possible :/ we could not wrap lines if that would be a problem.

**Comment by seratch** [comment]
hmm, I really like your wrapping idea but the behavior should be similar to editors.

#### Visual Studio Code

Screen Shot 2020-09-29 at 10 37 26

#### PyCharm (IntelliJ IDEA)

Screen Shot 2020-09-29 at 10 37 33

**Comment by shaydewael** [comment]
@seratch Yes I see your point. Let's close this for now, and we can revisit the idea later with a more comprehensive solution

**Pull request closed without merging**
